#/vis/open VRML2FILE
/vis/open OGL
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume

# /vis/viewer/set/background white
/vis/viewer/set/style wireframe
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
# /vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
# /vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 3

/vis/scene/endOfEventAction accumulate

/vis/viewer/flush

# /vis/viewer/set/rotationStyle freeRotation
# /vis/viewer/set/viewpointThetaPhi 269.999 -90.

#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
