##############
# param.conf #
##############

###### ~~~~~~~ Output information ~~~~~~~
ROOTFile: ../analysis/root/test.root

###### ~~~~~~~ Geometry & Magnetic filed ~~~~~~~~~ 
DCGEO: param/DCgeom.RealSts
#DCGEO:    Param/DCgeom.param_sts
#CHARGE:    1.0
BMAP: param/StsMap2500A.dat
Mag_Scale: 1.0
Mag_Scale_Q1: 1.0
Mag_Scale_Q2: 1.0

###### ~~~~~~~ Target ~~~~~~~~~ 
TPOSZ[mm]: 600 #E70 target position
#TPOSZ[mm]: 720 #E90 target position
#TARGET: 12
#TTHICKNESS[g/cm2]: 3
TARGET: 2222 # vacuum
TTHICKNESS[g/cm2]: 3


###### ~~~~~~~ PrimaryGeneratorAction for S2S ~~~~~
Generator: 1 #UnifomGenaration 
#Generator: 2 #FocusCheck 
GenMomCent[GeV/c]: 1.37
#GenMomBite[GeV/c]: 0.45
GenMomBite[GeV/c]: 0.975
#GenTheta[deg]: 25.0
#GenTheta[deg]: 23.0
GenTheta[deg]: 5.0
#GenPID --> 1:K+ 2:K- 3:pi+ 4:pi- 5:p 6:e- 7:mu- 8:xi-
GenPID: 1
#BeamWidth[mm]: 0.0 0.0 16.66666
BeamWidth[mm]: 0.0 0.0 0.0


###### ~~~~~ Physics Process ~~~~~~~~
EM: 0
DECAY: 0
HADRON: 0


###### ~~~~~ TOF dector ~~~~~~~
# NO zig-zag --> 
#TOF_OVERLAP[mm]: -2.0
#TOF_DISTANCE[mm]: -20.0

# Zig-zag --> 
TOF_OVERLAP[mm]: 4.0
TOF_DISTANCE[mm]: 0.0


