/control/verbose 2
/run/verbose 2
#/gun/particle e-
#/gun/particle proton
#/gun/particle kaon+
#/gun/particle pi+
#/gun/particle kaon+

#30min
#/run/beamOn 1000000

#/run/beamOn 100000

#/run/beamOn 50000

# /run/beamOn 50


#/vis/open VRML2FILE
/vis/open OGL
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume

# /vis/viewer/set/background white
/vis/viewer/set/style wireframe
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
# /vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
# /vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 3

/vis/scene/endOfEventAction accumulate

/vis/viewer/flush

# /vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/viewpointThetaPhi 269.999 -90.

#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
