#
# default.conf
#

Experiment:	10

DCGEO:		param/DCGEO/DCGeomParam_e10_20231019
DSIZE:		param/DSIZE/DetSize_E10_0
HIST:		param/HIST/HistParam_E10_0
FLDMAP:		fieldmap/BH14full_20230711.dat
Q1SCALE:	0.7
Q2SCALE:	0.7
D1SCALE:	0.65

###### PhysicsList
EM:		0
DECAY: 		0
HADRON: 	0

Generator: 	0

TargetMaterial: Be
# TargetMaterial: C

CheckOverlap:	0

TREE:		1
