#
# e70_BeamThrough.conf
#

Experiment:	70

#DCGEO:		param/DCGEO/DCgeom.20230917test
DCGEO:		param/DCGEO/DCGeomParam_e70_20230810
#DCGEO:		param/DCGEO/DCGeomParam_e10_20231019
DSIZE:		param/DSIZE/DetSize_E70_240717
HIST:		param/HIST/HistParam_E70_240410
# FLDMAP:		fieldmap/StsFieldMap_20230731_BH14full_D1_2362A.dat
# FLDMAP:		fieldmap/BH14full_20230711.dat
FLDMAP:		fieldmap_kevata/test_D-reduced_20230913_1cm.dat
Q1SCALE:	1.0
Q2SCALE:	1.0
D1SCALE:	1.0

###### PhysicsList
EM:		1
DECAY: 		0
HADRON: 	0

Generator: 	4	
K18ROOT: 	../../analyzer/e70/output/K18Track/root/K71479.root	

TargetMaterial: HeGas 
# TargetMaterial: CH2

CheckOverlap:	1

TREE:		1
