#
# e90_woHD.conf
#
# updated: 2025-11-25 k.amemiya

Experiment:	90

DCGEO:		param/DCGEO/DCGeomParam_E90_20250615
DSIZE:		param/DSIZE/DetSize_E90_20250615
HIST:		param/HIST/HistParam_E90_0
FLDMAP:         fieldmap/S2sFieldMap_pro.dat
Q1SCALE:	0.82
Q2SCALE:	1.0
D1SCALE:	0.82

###### PhysicsList
EM:		1
DECAY: 		1
HADRON: 	0

Generator:  9001 # GenerateSigmaNCusp
# Generator:  9002 # GenerateQFLambda
# Generator:  9003 # GenerateQFSigmaZ
# Generator:  9004 # GenerateQFSigmaP

# TargetMaterial: Be
TargetMaterial: LD2
# TargetMaterial: C

CheckOverlap:	1

TREE:		1
StopAtIron:	1
