#
# e90_demo.conf
#

Experiment:	90

DCGEO:		param/DCGEO/DCGeomParam_E90_20250615
DSIZE:		param/DSIZE/DetSize_E90_20250615
HIST:		param/HIST/HistParam_E90_0
# FLDMAP:		fieldmap/StsFieldMap_20230731_BH14full_D1_2362A.dat
# FLDMAP:		fieldmap/BH14full_20230711.dat
FLDMAP:         fieldmap/S2sFieldMap_pro.dat
Q1SCALE:	0.82
Q2SCALE:	1.0
D1SCALE:	0.82

###### PhysicsList
EM:		1
DECAY: 		0
HADRON: 	0

Generator: 	0

# TargetMaterial: Be
TargetMaterial: LD2
# TargetMaterial: C

CheckOverlap:	1

TREE:		1
StopAtIron:	1
