#
# e90_woHD.conf
#
# comments
# 2025-12-2 : updated DSIZE (kohki amemiya)

Experiment:	90

DCGEO:		param/DCGEO/DCGeomParam_E90_20250615
DSIZE:		param/DSIZE/DetSize_E90_20251202
HIST:		param/HIST/HistParam_E90_0
FLDMAP:     fieldmap/S2sFieldMap_pro.dat
Q1SCALE:	-0.82
Q2SCALE:	-1.0
D1SCALE:	-0.845

###### PhysicsList
EM:		1
DECAY: 		1
HADRON: 	0

Generator:  9001 # GenerateSigmaNCusp
# Generator:  9002 # GenerateQFLambda
# Generator:  9003 # GenerateQFSigmaZ
# Generator:  9004 # GenerateQFSigmaP

# Generator: 9010 # proton beam
# Momentum: 0.38 # for 9010 Generator

TargetMaterial: LD2

CheckOverlap:	1

TREE:		1
StopAtIron:	1
