#
# conf for E90 Machine Learning
#
# comments
# 2025-12-9 : 

Experiment:	90

DCGEO:		param/DCGEO/DCGeomParam_E90_20250615
DSIZE:		param/DSIZE/DetSize_E90_ML
HIST:		param/HIST/HistParam_E90_0 # not is use
FLDMAP:     fieldmap/S2sFieldMap_pro.dat
Q1SCALE:	-0.82
Q2SCALE:	-1.0
D1SCALE:	-0.845

###### PhysicsList
EM:		1
DECAY: 		1
HADRON: 	0

Generator:  9001 # GenerateSigmaNCusp
# Generator:  9002 # GenerateQFLambda
# Generator:  9003 # GenerateQFSigmaZ

TPCMt: 2   # TPC Multiplicity
Trunc: 0.3 # Truncated mean ratio for dE/dx
MinHit: 4  # Minimum TPC pad hits to accept as a track

TargetMaterial: LD2

CheckOverlap:	1

TREE:		1
BranchStyle: E90ML
StopAtIron:	1
